
#---------------Ansible EC2 Creation----------------
---
- name: Create a new Demo EC2 instance
  hosts: localhost
  gather_facts: False

  vars:
      region: ap-south-1
      instance_type: t2.micro
      ami: ami-0a74bfeb190bd404f  # Redhat
      keypair: aws-demo-4 # pem file name

  tasks:

    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         aws_access_key: "{{ my_access_key }}"
         aws_secret_key: "{{ my_secret_key }}"
         group: launch-wizard-5  # security group name
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1  # default
         count_tag:
            Name: "Ansible_Demo_7"
         instance_tags:
            Name: "Aws-Demo-7"
         vpc_subnet_id: "subnet-ced25b82"
         assign_public_ip: yes
      register: ec2
#boto required 

   - debug: var=ec2

   - debug:
      msg: "{{ item['private_ip'] }}"
      with_items: "{{ ec2.instances }}"

   - name: Add all web instance IPs to host group
      add_host: 
      hostname: "{{ item.private_ip }}"
      groupname: webservers
      ansible_user: ec2-user 
      with_items: '{{ ec2.instances }}'

  - name: Wait for SSH to come up
    wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
    with_items: '{{ ec2.instances }}'


