---
- name: start tomcat on remote
  command: /usr/local/apache-tomcat-8.0.23/bin/startup.sh
  register: startupchk 

- name: check variable
  debug: var=startupchk

- name: curl comamnd
  command: curl http://localhost:8080
  register: check

#- name: debugging
#  debug: var=check




